package server

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders the route / security matrix from the registry, so the
// documentation cannot drift from the code (a test compares it with
// docs/ROUTE_SECURITY_MATRIX.md).
func (r *Router) Markdown() string {
	routes := append([]RouteInfo(nil), r.Routes...)

	pathOf := func(pattern string) string {
		_, p, _ := strings.Cut(pattern, " ")
		return p
	}

	sort.SliceStable(routes, func(i, j int) bool {
		a, b := pathOf(routes[i].Pattern), pathOf(routes[j].Pattern)
		if a != b {
			return a < b
		}
		return routes[i].Pattern < routes[j].Pattern
	})

	counts := map[string]int{}
	for _, route := range routes {
		counts[route.Access]++
	}

	var b strings.Builder

	fmt.Fprintln(&b, "# API route / security matrix")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Generated by `go run ./cmd/route-matrix` from the router registry; the integration test")
	fmt.Fprintln(&b, "`TestRouteSecurityMatrix` exercises every row (401 without a token, 403 without the role),")
	fmt.Fprintln(&b, "and `TestRouteMatrixDocumentIsCurrent` fails when this file is out of date.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| Access class | Meaning | Routes |")
	fmt.Fprintln(&b, "|---|---|---|")
	fmt.Fprintf(&b, "| `public` | no token | %d |\n", counts[AccessPublic])
	fmt.Fprintf(&b, "| `session` | valid token for an active account, no role needed (own session only) | %d |\n", counts[AccessSession])
	fmt.Fprintf(&b, "| `authenticated` | active account holding at least one role (\"staff\"); self sign-ups see nothing until given a role | %d |\n", counts[AccessAuth])
	fmt.Fprintf(&b, "| `roles` | one of the listed roles | %d |\n", counts[AccessRoles])
	fmt.Fprintf(&b, "| `self_or_roles` | the user themself, otherwise one of the listed roles | %d |\n", counts[AccessSelfOrRoles])
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| Route | Access | Roles |")
	fmt.Fprintln(&b, "|---|---|---|")

	for _, route := range routes {
		roles := ""
		if len(route.Roles) > 0 {
			roles = "`" + strings.Join(route.Roles, "`, `") + "`"
		}

		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", route.Pattern, route.Access, roles)
	}

	return b.String()
}
