package billing

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// =========================================================
// SHARED PDF HELPERS
// =========================================================

type pdfDoc struct {
	*fpdf.Fpdf
	tr func(string) string
}

func newPDF() *pdfDoc {
	p := fpdf.New("P", "mm", "Letter", "")
	p.SetMargins(8, 8, 8)
	p.SetAutoPageBreak(false, 8)
	p.SetCreator("EHR Billing", true)

	return &pdfDoc{Fpdf: p, tr: p.UnicodeTranslatorFromDescriptor("")}
}

func (p *pdfDoc) text(x, y float64, size float64, style, value string) {
	p.SetFont("Helvetica", style, size)
	p.Text(x, y, p.tr(value))
}

// box draws a labeled field: a small item label in the corner and the value
// beneath it, clipped to the box width.
func (p *pdfDoc) box(x, y, w, h float64, label, value string) {
	p.SetDrawColor(120, 120, 120)
	p.Rect(x, y, w, h, "D")

	p.SetTextColor(90, 90, 90)
	p.text(x+0.8, y+2.6, 5.5, "", label)

	p.SetTextColor(0, 0, 0)
	p.SetFont("Helvetica", "B", 8.5)

	lines := strings.Split(value, "\n")
	for i, line := range lines {
		ty := y + 6.5 + float64(i)*3.6
		if ty > y+h-0.5 {
			break
		}
		p.Text(x+1.2, ty, p.tr(p.fit(line, w-2.4)))
	}
}

// fit truncates text so it fits within width w at the current font.
func (p *pdfDoc) fit(value string, w float64) string {
	for value != "" && p.GetStringWidth(p.tr(value)) > w {
		value = value[:len(value)-1]
	}

	return value
}

func (p *pdfDoc) output() ([]byte, string, error) {
	var buf bytes.Buffer

	if err := p.Output(&buf); err != nil {
		return nil, "", err
	}

	sum := sha256.Sum256(buf.Bytes())

	return buf.Bytes(), hex.EncodeToString(sum[:]), nil
}

func upper(value string) string {
	return strings.ToUpper(value)
}

// mmddyyyy formats an ISO date as MM DD YYYY (CMS-1500 style).
func mmddyyyy(iso string) string {
	t, err := time.Parse("2006-01-02", iso)
	if err != nil {
		return ""
	}

	return t.Format("01 02 2006")
}

func check(selected bool) string {
	if selected {
		return "[X]"
	}

	return "[ ]"
}

func personName(last, first, middle string) string {
	name := upper(last)
	if first != "" {
		name += ", " + upper(first)
	}
	if middle != "" {
		name += " " + upper(middle[:1])
	}

	return name
}

func addressLines(a SnapshotAddress, phone string) string {
	street := upper(a.Address1)
	if a.Address2 != "" {
		street += " " + upper(a.Address2)
	}

	out := street + "\n" + upper(a.City) + "  " + upper(a.State) + "  " + a.Zip
	if phone != "" {
		out += "\nPHONE " + phone
	}

	return out
}

func moneyParts(cents int64) string {
	return fmt.Sprintf("%d %02d", cents/100, cents%100)
}

// =========================================================
// CMS-1500 COMPATIBLE LAYOUT
// =========================================================

// cms1500Data is everything the CMS-1500 layout prints. It comes entirely
// from the claim snapshot and snapshotted claim lines.
type cms1500Data struct {
	ClaimNumber   string
	Snapshot      ClaimSnapshot
	Lines         []ClaimLine
	Diagnoses     []ClaimDiagnosis
	FrequencyCode string
	OriginalRef   string
	AmountPaid    int64
	GeneratedAt   time.Time
}

const cms1500Disclaimer = "CMS-1500 (02/12)-compatible field layout generated by this application. " +
	"This is NOT the official red OCR CMS-1500 form; payers that require the official form " +
	"should receive this data printed on pre-printed CMS-1500 stock."

const cmsLinesPerPage = 6

func frequencyCodeFor(resubmissionType string) string {
	switch resubmissionType {
	case "amended":
		return "7"
	case "void":
		return "8"
	}

	return "1"
}

// renderCMS1500 renders a claim on as many pages as needed (6 lines per
// page). Each page carries the totals for its own lines.
func renderCMS1500(d cms1500Data) ([]byte, string, int, error) {
	p := newPDF()
	s := d.Snapshot

	pages := (len(d.Lines) + cmsLinesPerPage - 1) / cmsLinesPerPage
	if pages == 0 {
		pages = 1
	}

	for page := 0; page < pages; page++ {
		p.AddPage()

		start := page * cmsLinesPerPage
		end := min(start+cmsLinesPerPage, len(d.Lines))
		lines := d.Lines[start:end]

		// ---- Header / carrier block
		p.SetTextColor(0, 0, 0)
		p.text(8, 12, 12, "B", "HEALTH INSURANCE CLAIM FORM")
		p.text(8, 16, 6.5, "", "CMS-1500 (02/12) COMPATIBLE FIELD LAYOUT - NOT AN OFFICIAL CMS FORM")

		carrier := upper(s.Payer.Name) + "\n" + addressLines(s.Payer.Address, "")
		p.box(128, 8, 80, 18, "CARRIER", carrier)

		y := 28.0

		// ---- Items 1 / 1a
		t := s.Payer.InsuranceType
		insType := fmt.Sprintf(
			"%s MEDICARE   %s MEDICAID   %s TRICARE   %s CHAMPVA\n%s GROUP HEALTH PLAN   %s FECA BLK LUNG   %s OTHER",
			check(t == "medicare"), check(t == "medicaid"), check(t == "tricare"), check(t == "champva"),
			check(t == "group_health_plan"), check(t == "feca_black_lung"), check(t == "other" || t == ""),
		)
		p.box(8, y, 130, 12, "1. INSURANCE TYPE", insType)
		p.box(138, y, 70, 12, "1a. INSURED'S I.D. NUMBER", upper(s.Insured.MemberID))
		y += 12

		// ---- Items 2 / 3 / 4
		p.box(8, y, 80, 10, "2. PATIENT'S NAME (Last, First, MI)", personName(s.Patient.LastName, s.Patient.FirstName, s.Patient.MiddleName))
		p.box(88, y, 50, 10, "3. PATIENT'S BIRTH DATE / SEX", mmddyyyy(s.Patient.DateOfBirth)+"   "+s.Patient.Sex)
		p.box(138, y, 70, 10, "4. INSURED'S NAME (Last, First, MI)", personName(s.Insured.LastName, s.Insured.FirstName, s.Insured.MiddleName))
		y += 10

		// ---- Items 5 / 6 / 7
		rel := s.Insured.Relationship
		relationship := fmt.Sprintf("%s SELF  %s SPOUSE\n%s CHILD  %s OTHER",
			check(rel == "self"), check(rel == "spouse"), check(rel == "child"), check(rel == "other"))
		p.box(8, y, 80, 17, "5. PATIENT'S ADDRESS", addressLines(s.Patient.Address, s.Patient.Phone))
		p.box(88, y, 50, 17, "6. PATIENT RELATIONSHIP TO INSURED", relationship)
		p.box(138, y, 70, 17, "7. INSURED'S ADDRESS", addressLines(s.Insured.Address, ""))
		y += 17

		// ---- Items 9 / 10 / 11
		var other SnapshotOtherInsurance
		hasOther := len(s.OtherInsurance) > 0
		if hasOther {
			other = s.OtherInsurance[0]
		}

		p.box(8, y, 80, 10, "9. OTHER INSURED'S NAME", upper(other.InsuredName))
		p.box(88, y, 50, 10, "10. CONDITION RELATED TO: EMPL / AUTO / OTHER", "NO / NO / NO")
		p.box(138, y, 70, 10, "11. INSURED'S POLICY GROUP OR FECA NUMBER", upper(s.Insured.PolicyGroup))
		y += 10

		otherPolicy := ""
		if hasOther {
			otherPolicy = upper(other.MemberID + " " + other.PolicyGroup)
		}
		p.box(8, y, 80, 10, "9a. OTHER INSURED'S POLICY OR GROUP NUMBER", otherPolicy)
		p.box(88, y, 50, 10, "10d. CLAIM CODES", "")
		p.box(138, y, 70, 10, "11a. INSURED'S DATE OF BIRTH / SEX", mmddyyyy(s.Insured.DateOfBirth)+"   "+s.Insured.Sex)
		y += 10

		p.box(8, y, 80, 10, "9d. OTHER INSURANCE PLAN NAME", upper(other.PayerName))
		p.box(88, y, 50, 10, "11c. INSURANCE PLAN NAME", upper(s.Insured.PlanName))
		anotherPlan := "NO"
		if hasOther {
			anotherPlan = "YES"
		}
		p.box(138, y, 70, 10, "11d. IS THERE ANOTHER HEALTH BENEFIT PLAN?", anotherPlan)
		y += 10

		// ---- Items 12 / 13
		signature := ""
		if s.Insured.SignatureOnFile {
			signature = "SIGNATURE ON FILE"
		}
		p.box(8, y, 130, 9, "12. PATIENT'S OR AUTHORIZED PERSON'S SIGNATURE", signature)
		p.box(138, y, 70, 9, "13. INSURED'S OR AUTHORIZED PERSON'S SIGNATURE", signature)
		y += 9

		// ---- Items 14-20 (not tracked by this application)
		p.box(8, y, 50, 9, "14. DATE OF CURRENT ILLNESS", "")
		p.box(58, y, 40, 9, "15. OTHER DATE", "")
		p.box(98, y, 50, 9, "16. DATES UNABLE TO WORK", "")
		p.box(148, y, 60, 9, "18. HOSPITALIZATION DATES", "")
		y += 9
		p.box(8, y, 90, 9, "17. NAME OF REFERRING PROVIDER", "")
		p.box(98, y, 70, 9, "19. ADDITIONAL CLAIM INFORMATION", "")
		p.box(168, y, 40, 9, "20. OUTSIDE LAB?", "NO")
		y += 9

		// ---- Items 21 / 22 / 23
		var dx strings.Builder
		for i, diagnosis := range d.Diagnoses {
			if i > 0 && i%4 == 0 {
				dx.WriteString("\n")
			} else if i > 0 {
				dx.WriteString("    ")
			}
			fmt.Fprintf(&dx, "%s. %s", diagnosis.Letter, strings.ReplaceAll(diagnosis.ICD10Code, ".", ""))
		}
		p.box(8, y, 130, 16, "21. DIAGNOSIS OR NATURE OF ILLNESS OR INJURY (ICD Ind. 0)", dx.String())

		resubmission := ""
		if d.FrequencyCode != "1" {
			resubmission = d.FrequencyCode + "    " + upper(d.OriginalRef)
		}
		p.box(138, y, 70, 8, "22. RESUBMISSION CODE / ORIGINAL REF. NO.", resubmission)

		authorization := ""
		for _, l := range d.Lines {
			if l.PriorAuthorizationCode != "" {
				authorization = upper(l.PriorAuthorizationCode)
				break
			}
		}
		p.box(138, y+8, 70, 8, "23. PRIOR AUTHORIZATION NUMBER", authorization)
		y += 16

		// ---- Item 24 service lines
		headers := []struct {
			label string
			w     float64
		}{
			{"24A. DATE(S) OF SERVICE", 38}, {"B. POS", 12}, {"C. EMG", 10}, {"D. CPT/HCPCS  MODIFIER", 42},
			{"E. DX PTR", 16}, {"F. $ CHARGES", 26}, {"G. UNITS", 14}, {"H. EPSDT", 10}, {"I. QUAL", 10}, {"J. RENDERING NPI", 22},
		}

		x := 8.0
		for _, h := range headers {
			p.box(x, y, h.w, 6, h.label, "")
			x += h.w
		}
		y += 6

		var pageTotal int64

		for i := 0; i < cmsLinesPerPage; i++ {
			var cells []string

			if i < len(lines) {
				l := lines[i]
				total := mustCents(l.LineTotal)
				pageTotal += total

				code := upper(l.ServiceCode)
				if len(l.Modifiers) > 0 {
					code += "  " + strings.Join(l.Modifiers, " ")
				}

				cells = []string{
					mmddyyyy(l.DateOfService) + "  " + mmddyyyy(l.DateOfService),
					l.PlaceOfService, "", code, l.DiagnosisPointers, moneyParts(total),
					fmt.Sprint(l.Units), "", "NPI", l.RenderingNPI,
				}
			} else {
				cells = make([]string, len(headers))
			}

			x = 8.0
			for j, h := range headers {
				p.box(x, y, h.w, 8, "", cells[j])
				x += h.w
			}
			y += 8
		}

		// ---- Items 25-30
		taxType := fmt.Sprintf("%s SSN %s EIN", check(s.Practice.TaxIDType == "ssn"), check(s.Practice.TaxIDType != "ssn"))
		p.box(8, y, 52, 10, "25. FEDERAL TAX I.D. NUMBER", s.Practice.TaxID+"  "+taxType)
		p.box(60, y, 40, 10, "26. PATIENT'S ACCOUNT NO.", upper(s.Patient.AccountNumber))
		p.box(100, y, 28, 10, "27. ACCEPT ASSIGNMENT?", "YES")
		p.box(128, y, 28, 10, "28. TOTAL CHARGE", moneyParts(pageTotal))

		paid := ""
		if d.AmountPaid > 0 && page == 0 {
			paid = moneyParts(d.AmountPaid)
		}
		p.box(156, y, 26, 10, "29. AMOUNT PAID", paid)
		p.box(182, y, 26, 10, "30. RSVD FOR NUCC USE", "")
		y += 10

		// ---- Items 31-33
		p.box(8, y, 60, 22, "31. SIGNATURE OF PHYSICIAN OR SUPPLIER", "SIGNATURE ON FILE\nDATE "+d.GeneratedAt.Format("01 02 2006"))
		p.box(68, y, 70, 22, "32. SERVICE FACILITY LOCATION / 32a. NPI",
			upper(s.Practice.Name)+"\n"+addressLines(s.Practice.Address, "")+"\nNPI "+s.Practice.NPI)
		p.box(138, y, 70, 22, "33. BILLING PROVIDER INFO & PH # / 33a. NPI",
			upper(s.Practice.Name)+"\n"+addressLines(s.Practice.Address, s.Practice.Phone)+"\nNPI "+s.Practice.NPI)
		y += 24

		// ---- Footer
		p.SetTextColor(70, 70, 70)
		p.text(8, y, 6.5, "", fmt.Sprintf("Claim %s  |  Page %d of %d  |  Generated %s",
			d.ClaimNumber, page+1, pages, d.GeneratedAt.Format("2006-01-02 15:04 MST")))
		p.SetXY(8, y+1.5)
		p.SetFont("Helvetica", "", 6)
		p.MultiCell(200, 2.8, p.tr(cms1500Disclaimer), "", "L", false)
	}

	bytes, sum, err := p.output()

	return bytes, sum, pages, err
}

// =========================================================
// SUPERBILL
// =========================================================

type superbillLine struct {
	ChargeID       string   `json:"charge_id"`
	DateOfService  string   `json:"date_of_service"`
	ServiceCode    string   `json:"service_code"`
	Description    string   `json:"description"`
	Modifiers      []string `json:"modifiers"`
	Units          int      `json:"units"`
	PlaceOfService string   `json:"place_of_service"`
	Diagnoses      string   `json:"diagnoses"`
	Fee            string   `json:"fee"`
	Paid           string   `json:"paid"`
	Clinician      string   `json:"clinician"`
	ClinicianNPI   string   `json:"clinician_npi"`
}

type superbillData struct {
	Practice    SnapshotPractice `json:"practice"`
	Patient     SnapshotPerson   `json:"patient"`
	Diagnoses   []ClaimDiagnosis `json:"diagnoses"`
	Lines       []superbillLine  `json:"lines"`
	TotalFees   string           `json:"total_fees"`
	TotalPaid   string           `json:"total_paid"`
	GeneratedAt string           `json:"generated_at"`
}

func renderSuperbill(d superbillData) ([]byte, string, error) {
	p := newPDF()
	p.AddPage()
	p.SetTextColor(0, 0, 0)

	p.text(8, 14, 15, "B", "SUPERBILL / STATEMENT OF SERVICES")
	p.text(8, 19, 7, "", "Itemized record of services for submission to your insurance. This is not a bill from your insurer.")

	p.box(8, 24, 100, 24, "PROVIDER / PRACTICE",
		d.Practice.Name+"\n"+addressLines(d.Practice.Address, d.Practice.Phone)+
			fmt.Sprintf("\nNPI %s   TAX ID (%s) %s", d.Practice.NPI, upper(d.Practice.TaxIDType), d.Practice.TaxID))
	p.box(108, 24, 100, 24, "PATIENT",
		personName(d.Patient.LastName, d.Patient.FirstName, d.Patient.MiddleName)+
			"\nDOB "+mmddyyyy(d.Patient.DateOfBirth)+"\n"+addressLines(d.Patient.Address, ""))

	y := 52.0
	p.text(8, y, 9, "B", "DIAGNOSES")
	y += 4
	for _, dx := range d.Diagnoses {
		p.text(10, y, 8, "", fmt.Sprintf("%s.  %s  %s", dx.Letter, dx.ICD10Code, dx.Description))
		y += 4
	}

	y += 3
	columns := []struct {
		label string
		w     float64
	}{
		{"DATE", 20}, {"CODE", 18}, {"MOD", 12}, {"DESCRIPTION", 44}, {"POS", 10}, {"DX", 10},
		{"UNITS", 11}, {"PROVIDER (NPI)", 43}, {"FEE", 16}, {"PAID", 16},
	}

	p.SetFillColor(235, 235, 235)
	p.SetFont("Helvetica", "B", 7)
	x := 8.0
	for _, c := range columns {
		p.SetXY(x, y)
		p.CellFormat(c.w, 6, c.label, "1", 0, "L", true, 0, "")
		x += c.w
	}
	y += 6

	p.SetFont("Helvetica", "", 7)

	for _, l := range d.Lines {
		if y > 255 {
			p.AddPage()
			y = 12
		}

		cells := []string{
			l.DateOfService, l.ServiceCode, strings.Join(l.Modifiers, " "), l.Description, l.PlaceOfService,
			l.Diagnoses, fmt.Sprint(l.Units), l.Clinician + " (" + l.ClinicianNPI + ")", "$" + l.Fee, "$" + l.Paid,
		}

		x = 8.0
		for i, c := range columns {
			p.SetXY(x, y)
			align := "L"
			if i >= 8 {
				align = "R"
			}
			p.CellFormat(c.w, 6, p.tr(p.fit(cells[i], c.w-1.5)), "1", 0, align, false, 0, "")
			x += c.w
		}
		y += 6
	}

	y += 4
	p.text(150, y, 9, "B", "Total fees: $"+d.TotalFees)
	p.text(150, y+5, 9, "B", "Total paid: $"+d.TotalPaid)

	p.SetTextColor(70, 70, 70)
	p.text(8, 272, 6.5, "", "Generated "+d.GeneratedAt+". Provider signature on file.")

	return p.output()
}
